yourFood = input("Name a food: ")
yourPlant = input("Name a type of plant: ")
yourCooking = input("Name a method of cooking: ")
yourBurned = input("What word describes burned food?: ")
yourDIY = input("Name a DIY item: ")
print()
print("MENU")
print(yourCooking, yourFood, "with", yourBurned, yourPlant, "on a bed of", yourDIY)
